export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const;
